version: '3.4'

services:
  solidbookmarker:
    container_name: solidbookmarker
    # image: solidbookmarker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4300:80